- hosts: terraform-ansible
  tasks:
    - name: Instalando o python3 e VirtualEnv
      apt:
        pkg: 
        - python3
        - virtualenv
        update-cache: yes # atualiza os repositorios
      become: yes # instala os pacotes como root
    - name: Instalando dependencias com pip (Django e Django Rest)
      pip:
        virtualenv: ~/tcc/venv
        name:
          - django
          - djangorestframework
    - name: Iniciando projeto
      shell: '. /home/ubuntu/tcc/venv/bin/activate; django-admin startproject setup /home/ubuntu/tcc/'